# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: park.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npark.proto\x12\x04park\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"!\n\x0f\x43ommandResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2O\n\x0e\x43\x61rParkService\x12=\n\x0eProcessCommand\x12\x14.park.CommandRequest\x1a\x15.park.CommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'park_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_start=20
  _globals['_COMMANDREQUEST']._serialized_end=53
  _globals['_COMMANDRESPONSE']._serialized_start=55
  _globals['_COMMANDRESPONSE']._serialized_end=88
  _globals['_CARPARKSERVICE']._serialized_start=90
  _globals['_CARPARKSERVICE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
